[package]
name = "player-client"
version = "0.1.0"
edition = "2021"

[dependencies]
shared = {path = "../shared"}
color-eyre = "0.6.4"
serde_json = "1.0.140"
tokio = { version = "1.44.2", features = ["full"] }
